name: kumoriya_source_animeav1
description: AnimeAV1 source plugin implementation for Kumoriya.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  html: ^0.15.6
  http: ^1.5.0
  kumoriya_core:
  kumoriya_domain:
  kumoriya_plugins:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
