name: kumoriya_resolver_mp4upload
description: Mp4Upload host resolver plugin for Kumoriya.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  http: ^1.2.2
  kumoriya_core:
  kumoriya_plugins:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
