name: kumoriya_app
description: Kumoriya main Flutter application.
publish_to: none
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^3.0.3
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  kumoriya_anilist:
  kumoriya_core:
  kumoriya_domain:
  kumoriya_plugins:
  kumoriya_matching:
  kumoriya_source_jkanime:
  kumoriya_source_animeflv:
  kumoriya_source_animeav1:
  kumoriya_source_anime_nexus:
  kumoriya_resolver_jkplayer:
  kumoriya_resolver_streamwish:
  kumoriya_resolver_mp4upload:
  kumoriya_resolver_pixeldrain:
  kumoriya_resolver_streamtape:
  kumoriya_resolver_doodstream:
  kumoriya_resolver_yourupload:
  kumoriya_resolver_okru:
  kumoriya_resolver_hqq:
  kumoriya_resolver_zilla:
  kumoriya_resolver_upnshare:
  kumoriya_resolver_anime_nexus:
  kumoriya_storage:
  drift:
  sqlite3_flutter_libs:
  path_provider:
  path:
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http: any
  workmanager: ^0.6.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.15

flutter:
  generate: true
  uses-material-design: true
